slug: dev
name: Dev
icon: fas fa-laptop-code
links:
  - url: https://htaccess.madewithlove.be/
    title: .htaccess tester
    icon: /img/htaccess.svg
  - url: https://repl.it/
    title: Repl.it - The collaborative browser based IDE
